# Generated by Django 3.2.5 on 2021-07-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playmodel', '0003_auto_20210702_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='invite_person',
            new_name='invite_reason',
        ),
    ]
